# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# trigger:
# - master

# pool:
#   vmImage: 'windows-latest'

# variables:
#   solution: '**/*.sln'
#   buildPlatform: 'Any CPU'
#   buildConfiguration: 'Release'

# steps:
# - task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'

# - task: VSBuild@1
#   inputs:
#     solution: '$(solution)'
#     msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

trigger:
  branches:
    include:
      - master 

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  solution: '**/VirginMediaWebApp/WebApplication1/*.sln'
  buildPlatform: 'Any CPU'
  publishDirectory: '$(Build.ArtifactStagingDirectory)/publish'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'

# Step 1: Restore NuGet packages
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Step 2: Build the solution
# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'build'
#     projects: '$(solution)'
#     arguments: '--configuration $(buildConfiguration)'

# Step 3: Run unit tests (optional, if you have tests)
- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    projects: '**/*.Tests.csproj' # Modify based on your test project structure
    arguments: '--configuration $(buildConfiguration) --no-build --verbosity normal'

# Step 4: Publish the Web Layer (Presentation Layer)
- task: DotNetCoreCLI@2
  displayName: 'Publish Web Project'
  inputs:
    command: 'build'
    projects: '**/VirginMediaWebApp/VirginMediaWebApp.csproj' 
    arguments: '--configuration Release'

# Step 5: Deploy to Azure Web App
- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'Azure subscription 1(1)(ce60c81e-f8ee-413a-a8fe-e84546574728)'
    appType: 'webApp'
    appName: 'NewTutorialWebApp' 
    package: '$(System.ArtifactsDirectory)/**/*.zip'
    runtimeStack: 'DOTNETCORE|8.0' 
    deploymentMethod: 'auto'

# Step 6: Publish other layers (if applicable)
- task: DotNetCoreCLI@2
  displayName: 'Publish Service Layer'
  inputs:
    command: 'publish'
    projects: '**/Service.csproj' 
    arguments: '--configuration $(buildConfiguration) --output $(publishDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'Publish Domain Layer'
  inputs:
    command: 'publish'
    projects: '**/Repository.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(publishDirectory)'


# Step 7: Artifact Publish (optional)
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(publishDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
